//<![CDATA[

(function(d){var n={speed:700,pause:4E3,showItems:1,mousePause:!0,height:0,animate:!0,margin:0,padding:0,startPaused:!1},c={moveUp:function(a,b){c.animate(a,b,"up")},moveDown:function(a,b){c.animate(a,b,"down")},animate:function(a,b,e){var c=a.itemHeight,f=a.options,k=a.element,g=k.children("ul"),l="up"===e?"li:first":"li:last";k.trigger("vticker.beforeTick");var m=g.children(l).clone(!0);0<f.height&&(c=g.children("li:first").height());c+=f.margin+2*f.padding;"down"===e&&g.css("top","-"+c+"px").prepend(m);
if(b&&b.animate){if(a.animating)return;a.animating=!0;g.animate("up"===e?{top:"-="+c+"px"}:{top:0},f.speed,function(){d(g).children(l).remove();d(g).css("top","0px");a.animating=!1;k.trigger("vticker.afterTick")})}else g.children(l).remove(),g.css("top","0px"),k.trigger("vticker.afterTick");"up"===e&&m.appendTo(g)},nextUsePause:function(){var a=d(this).data("state"),b=a.options;a.isPaused||2>a.itemCount||f.next.call(this,{animate:b.animate})},startInterval:function(){var a=d(this).data("state"),b=
this;a.intervalId=setInterval(function(){c.nextUsePause.call(b)},a.options.pause)},stopInterval:function(){var a=d(this).data("state");a&&(a.intervalId&&clearInterval(a.intervalId),a.intervalId=void 0)},restartInterval:function(){c.stopInterval.call(this);c.startInterval.call(this)}},f={init:function(a){f.stop.call(this);var b=jQuery.extend({},n);a=d.extend(b,a);var b=d(this),e={itemCount:b.children("ul").children("li").length,itemHeight:0,itemMargin:0,element:b,animating:!1,options:a,isPaused:a.startPaused?
!0:!1,pausedByCode:!1};d(this).data("state",e);b.css({overflow:"hidden",position:"relative"}).children("ul").css({position:"absolute",margin:0,padding:0}).children("li").css({margin:a.margin,padding:a.padding});isNaN(a.height)||0===a.height?(b.children("ul").children("li").each(function(){var a=d(this);a.height()>e.itemHeight&&(e.itemHeight=a.height())}),b.children("ul").children("li").each(function(){d(this).height(e.itemHeight)}),b.height((e.itemHeight+(a.margin+2*a.padding))*a.showItems+a.margin)):
b.height(a.height);var h=this;a.startPaused||c.startInterval.call(h);a.mousePause&&b.bind("mouseenter",function(){!0!==e.isPaused&&(e.pausedByCode=!0,c.stopInterval.call(h),f.pause.call(h,!0))}).bind("mouseleave",function(){if(!0!==e.isPaused||e.pausedByCode)e.pausedByCode=!1,f.pause.call(h,!1),c.startInterval.call(h)})},pause:function(a){var b=d(this).data("state");if(b){if(2>b.itemCount)return!1;b.isPaused=a;b=b.element;a?(d(this).addClass("paused"),b.trigger("vticker.pause")):(d(this).removeClass("paused"),
b.trigger("vticker.resume"))}},next:function(a){var b=d(this).data("state");if(b){if(b.animating||2>b.itemCount)return!1;c.restartInterval.call(this);c.moveUp(b,a)}},prev:function(a){var b=d(this).data("state");if(b){if(b.animating||2>b.itemCount)return!1;c.restartInterval.call(this);c.moveDown(b,a)}},stop:function(){d(this).data("state")&&c.stopInterval.call(this)},remove:function(){var a=d(this).data("state");a&&(c.stopInterval.call(this),a=a.element,a.unbind(),a.remove())}};d.fn.vTicker=function(a){if(f[a])return f[a].apply(this,
Array.prototype.slice.call(arguments,1));if("object"!==typeof a&&a)d.error("Method "+a+" does not exist on jQuery.vTicker");else return f.init.apply(this,arguments)}})(jQuery);

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('g O(t){v(b e=0;e<t.w;e++)b a=t[e].1T.$t;H a}g L(t){b e=[];e[1]="1G",e[2]="1u",e[3]="1e",e[4]="Z",e[5]="1t",e[6]="1n",e[7]="1m",e[8]="1g",e[9]="1i",e[10]="1l",e[11]="1k",e[12]="1j";b a=t.D(0,4),s=t.D(5,7),r=t.D(8,10),n=e[1h(s,10)]+" "+r+" "+a;H n}g T(e){b k=$(\'#c-d\'),q=e.1r.1q,m="<S 1o=\'1p-1f-1c\'>";x(q){v(b i=0;i<q.w;i++){b f=q[i];v(b j=0;j<f.u.w;j++){x(f.u[j].Y==\'W\'){b J=f.u[j].K;16}}1d{b C=\'<1b 1a="\'+f.17$18.U+\'"/>\'}19(e){b C=""}b M=f.1S.$t,y=O(f.y),P=L(f.1N.$t);m+=\'<R>\'+C+\'<Q><a K="\'+J+\'">\'+M+\'</a></Q><I B="1W"><l>\'+y+\'</l> - <l>\'+P+\'</l></I></R>\'}m+=\'</S>\';k.1C(m)}$(\'#c-d\').h();$(\'.c-d-k .1z\').A(g(){x($(z).1x(\'F\')){$(\'#c-d\').h(\'E\',1y);$(z).1D(\'F\').G(\'<i B="N-E"></i>\')}1E{$(\'#c-d\').h(\'E\',p);$(z).1K(\'F\').G(\'<i B="N-1B"></i>\')}});$(\'.c-d-k .1F\').A(g(){$(\'#c-d\').h(\'1H\',{V:p})});$(\'.c-d-k .1I\').A(g(){$(\'#c-d\').h(\'1J\',{V:p})})}$(g(){$.1w({1A:\'1M\',U:\'/1L/1U/1Y?1Z-1X=3&1V=o-1P-1O&1Q-1R=5\',1v:p,15:"X/o",14:\'13\',1s:g(o){T(o)}})});',62,124,'|||||||||||var|tl|ticker||en|function|vTicker|||con|span|item||json|true|entries||||link|for|length|if|author|this|click|class|Img|substring|pause|paused|html|return|div|postUrl|href|getmetaq|ti|fa|getauthorq|date|h3|li|ul|bloggerEverTicker|url|animate|alternate|application|rel|Apr||||jsonp|dataType|contentType|break|media|thumbnail|catch|src|img|inner|try|Mar|wrapper|Aug|parseInt|Sep|Dec|Nov|Oct|Jul|Jun|id|ticket|entry|feed|success|May|Feb|async|ajax|hasClass|false|pp|type|play|append|removeClass|else|down|Jan|next|up|prev|addClass|feeds|GET|published|script|in|start|index|title|name|posts|alt|tickermeta|results|summary|max'.split('|'),0,{}))


//]]>
